# Generated by Django 3.2.6 on 2021-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=20)),
                ('lastname', models.TextField(max_length=20)),
                ('username', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=1000)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
