# Generated by Django 3.2.6 on 2021-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0003_auto_20211117_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='static/Delicious_Images')),
            ],
        ),
    ]
