# Generated by Django 3.2.6 on 2021-11-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0004_icecreams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
