# Generated by Django 3.2.6 on 2021-11-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0005_delete_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IceCreams',
            new_name='IceCream',
        ),
    ]
