# Generated by Django 3.2.6 on 2021-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0006_rename_icecreams_icecream'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='catagory',
            field=models.CharField(default='ice-Creams', max_length=50),
        ),
    ]
