# Generated by Django 3.2.6 on 2021-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0007_icecream_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.TextField(max_length=50000)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=13)),
                ('amount', models.IntegerField(default=0)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
