# Generated by Django 3.2.6 on 2021-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delicious_Project_app', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='', max_length=8),
        ),
    ]
